version: '3.7'
services:
  pymorphosonic:
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
      labels:
        io.simcore.name: '{"name":"pymorphosonic"}'
        io.simcore.thumbnail: '{"thumbnail":"https://github.com/ITISFoundation/osparc-assets/blob/cb43207b6be2f4311c93cd963538d5718b41a023/assets/default-thumbnail-cookiecutter-osparc-service.png?raw=true"}'
        io.simcore.description: '{"description":"pymorphosonic"}'
        io.simcore.key: '{"key":"simcore/services/comp/pymorphosonic"}'
        io.simcore.version: '{"version":"0.1.0"}'
        io.simcore.integration-version: '{"integration-version":"1.0.0"}'
        io.simcore.type: '{"type":"computational"}'
        io.simcore.authors: '{"authors":[{"name":"Lucia Moya Sans","email":"moyasans@itis.swiss","affiliation":"ITIS
          Foundation"}]}'
        io.simcore.contact: '{"contact":"moyasans@itis.swiss"}'
        io.simcore.inputs: '{"inputs":{"input_1":{"displayOrder":1.0,"label":"input_1_label","description":"Input
          files (including a .py file)","type":"data:*/*"}}}'
        io.simcore.outputs: '{"outputs":{"output_1":{"displayOrder":1.0,"label":"output_1_label","description":"The
          input 1 description","type":"data:*/*"}}}'
        org.label-schema.build-date: 2025-03-10T10:41:52+0000
        org.label-schema.schema-version: '1.0'
        org.label-schema.vcs-ref: b0352e351e8e2023a988c502a7667039cbd13a7f
        org.label-schema.vcs-url: https://github.com/ITISFoundation/pymorphosonic
        simcore.service.restart-policy: no-restart
        simcore.service.paths-mapping: '{"inputs_path":"/home/scu/work/inputs","outputs_path":"/home/scu/work/outputs"}'
        simcore.service.settings: '[{"name":"constraints","type":"string","value":["node.platform.os
          == linux"]},{"name":"Resources","type":"Resources","value":{"Limits":{"NanoCPUs":1000000000,"MemoryBytes":2147483648}}}]'
      target: production
    image: simcore/services/comp/pymorphosonic:0.1.0
